[build]
  publish = "public"         # Serve static files from /public
  command = ""               # No build step

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"   # Keep default (safe even with no deps)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[scheduled]]
  path = "/.netlify/functions/cleanup_deploys"
  schedule = "@daily"
